Feat/clin 2095
Ferlab-Ste-Justine/users-api pull request #35
Opened 2023-07-27 17:14 UTC by ethienneroy

2023-07-31 14:17 UTC, evans-g-crsj requested changes

2023-07-31 14:17 UTC, evans-g-crsj commented on src/db/models/SavedFilter.ts
> +                isUUID: 4,
Magic number.
`const VERSION_4 = 4` ou` const UUID_VERSION = 4` ou ...
ou regarder dans la lib sequilize si il existe une constante que tu pourrais importer au lieu de t'en créer une

2023-07-31 14:17 UTC, evans-g-crsj commented on package.json
> +        "sequelize": "^6.28.2",
:+1:

2023-07-31 14:17 UTC, evans-g-crsj commented on src/db/models/User.ts
> +                len: [1, 20],
go with MAX=70

2023-07-31 14:17 UTC, evans-g-crsj commented on src/db/models/User.ts
> +                isAlpha: true,
alphanumeric

2023-07-31 14:17 UTC, evans-g-crsj commented on src/db/models/User.ts
Je pense qu'on devrait ajouter plus de validation de longeur, mais on pourra le faire dans un 2ième temps. Faut s'assurer que dans les BDs actuelles, on mette pas des contraintes qui ne soient pas compatibles avec le contenu de certains champs

2023-07-31 14:17 UTC, evans-g-crsj commented on src/db/models/UserSets.ts
> +                isUUID: 4,
même commentaire que plus haut

2023-07-31 16:14 UTC, celinepelletier approved these changes

2023-08-07 16:37 UTC, evans-g-crsj approved these changes

2023-08-07 16:38 UTC, merged