feat: SJIP-572 add shared endpoint to retrieve a set from another user
Ferlab-Ste-Justine/users-api pull request #62
Opened 2023-10-24 19:29 UTC by celinepelletier

2023-10-25 08:54 UTC, atoulous requested changes

2023-10-25 08:54 UTC, atoulous commented on src/routes/userSets.ts
> +        const result = await getByIdAndKeycloakId(keycloak_id, req.params.id);
l'ancienne methode tu la laisses comme ca sans changer le nom. Ca permet de ne pas avoir de regression. C'est la nouvelle que tu renames comme tu veux ! ;)

2023-10-25 08:55 UTC, atoulous commented on src/routes/userSets.ts
> +        const result = await getByIdAndKeycloakId(keycloak_id, req.params.id);
Ah moins que tu veuilles direct impacter tous les projets en meme temps, dans ce cas go

2023-10-27 14:28 UTC, evans-g-crsj approved these changes

2023-10-27 14:46 UTC, merged