feat: CQDG-836 add isPhantomManifest on user-set
Ferlab-Ste-Justine/users-api pull request #87
Opened 2024-08-29 19:22 UTC by atoulous

2024-08-29 19:41 UTC, celinepelletier requested changes

2024-08-29 19:41 UTC, celinepelletier commented on package-lock.json
> -    "lockfileVersion": 3,
Pourquoi tu downgrade de version de lock file ?

2024-08-29 19:45 UTC, atoulous commented on package-lock.json
> -    "lockfileVersion": 3,
je ne l'ai pas fais manuellement
je l'ai delete puis recréé car une lib avait une version de sous-lib qui passait pas le build Trivy:
https://github.com/Ferlab-Ste-Justine/users-api/actions/runs/10621348628/job/29443103086

2024-08-29 19:49 UTC, celinepelletier commented on package-lock.json
> -    "lockfileVersion": 3,
tu utilises une version de npm trop vieille alors < 9.X.Y, il faudrait mettre à jour ton npm et re-run ta cmd pour rester sur un lockfileVersion à 3

2024-08-29 19:50 UTC, celinepelletier commented on package-lock.json
> -    "lockfileVersion": 3,
Aussi pour réglé ce genre de problème de dep, tu peux faire un npm audit puis npm audit fix pour fixer, pas besoin de supprimer tout le package-lock

2024-08-29 20:08 UTC, atoulous commented on package-lock.json
> -    "lockfileVersion": 3,
Oui bien sur on peut faire un audit fix, mais supprimer le package-lock au complet permet aux deps de s'installer avec leurs dernieres versions mineurs (^)
ca permet de les garder + a jour.
dans ce cas précis la dep n'a meme plus besoin de axios donc axios n'est meme plus présent.
je privilégie cette méthode car l'audit fix l'aurai juste upgrade.

pour mon npm oui je suis sur la version 8, je peux l'update, mais je me demande a quoi te sert le lockfileVersion et si tu as deja rencontré des problèmes avec ca ?

2024-08-29 20:10 UTC, celinepelletier commented on package-lock.json
> -    "lockfileVersion": 3,
Pas de problème particulier sauf le fait qu'on a pas de raison de revenir à des versions plus anciennes de npm, lockfile version 2 c'est un smell qu'il a été buildé avec un "vieux" npm. Si pas de raison valable de downgrade a l'utilisation de npm 8 au lieu de 9, je resterai sur 9

2024-08-29 20:26 UTC, atoulous commented on package-lock.json
> -    "lockfileVersion": 3,
Ok alors j'ai repush un package-lock avec mon npm@9
et j'ai mis a jour la version recommandée dans le package.json qui était encore la 8.
```
"engines": {
    "node": ">=18.8.0",
    "npm": ">=9.9.3"
},
```

2024-08-29 20:27 UTC, celinepelletier approved these changes

2024-08-30 13:29 UTC, celinepelletier approved these changes

2024-09-10 21:35 UTC, merged